name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  TOKEN : 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
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker build . --file sample-packages/docker/Dockerfile --tag my-image-name:$(date +%s)
    - run: |
          export token='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'
          echo $token
          echo $token | docker login ghcr.io -u ankisingh243 --password-stdin
          docker tag IMAGE_ID ghcr.io/OWNER/IMAGE_NAME:latest
          docker push ghcr.io/OWNER/IMAGE_NAME:latest
