name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
    - run: docker build . --file sample-packages/docker/Dockerfile --tag my-image-name:$(date +%s)
    - run: | 
        echo $GITHUB_TOKEN | docker login ghcr.io -u USERNAME --password-stdin

        docker tag IMAGE_ID ghcr.io/OWNER/IMAGE_NAME:latest

        docker push ghcr.io/OWNER/IMAGE_NAME:latest
